const canvas=document.querySelector('#graph'),ctx=canvas.getContext('2d'),editor=document.querySelector('#code-input'),xMin=document.querySelector('#x-min'),xMax=document.querySelector('#x-max'),status=document.querySelector('#status'),errorBox=document.querySelector('#error-box'),legend=document.querySelector('#legend-code'),readout=document.querySelector('#coordinate-readout'),panel=document.querySelector('.graph-panel'),empty=document.querySelector('#empty-state');
const samples=1024,view={centerX:.5,centerY:.5,scale:430}; let evaluator=null,expression='smoothstep(x)',drag=null,cursor=null;
const helpers={abs:Math.abs,acos:Math.acos,asin:Math.asin,atan:Math.atan,ceil:Math.ceil,cos:Math.cos,exp:Math.exp,floor:Math.floor,log:Math.log,max:Math.max,min:Math.min,pow:Math.pow,round:Math.round,sign:Math.sign,sin:Math.sin,sqrt:Math.sqrt,tan:Math.tan,PI:Math.PI,saturate:v=>Math.min(1,Math.max(0,v)),clamp:(v,a,b)=>Math.min(b,Math.max(a,v)),lerp:(a,b,t)=>a+(b-a)*t,frac:v=>v-Math.floor(v),step:(a,v)=>v<a?0:1,smoothstep:(...v)=>{const[a,b,x]=v.length===1?[0,1,v[0]]:v;const t=Math.min(1,Math.max(0,(x-a)/(b-a)));return t*t*(3-2*t)}};
const args=Object.values(helpers);
function clean(source){let value=source.replace(/\/\/.*$/gm,'').trim();const returned=value.match(/return\s+([\s\S]*?);?\s*$/i);if(returned)value=returned[1];const assigned=value.match(/^(?:float\s+)?(?:y\s*=\s*)?([\s\S]*?)\s*;?$/i);if(assigned)value=assigned[1];return value.trim().replace(/\bfloat\b|\bhalf\b|\bfixed\b/gi,'').replace(/\^/g,'**')}
function compile(){try{expression=clean(editor.value);if(!expression)throw Error('请输入一个表达式。');evaluator=new Function('x',...Object.keys(helpers),'"use strict"; return ('+expression+');');const check=evaluator(.5,...args);if(!Number.isFinite(check))throw Error('表达式在 x = 0.5 时未返回有限数值。');status.textContent='已编译';status.dataset.state='ready';errorBox.hidden=true;legend.textContent='y = '+expression}catch(error){evaluator=null;status.textContent='编译错误';status.dataset.state='error';errorBox.textContent=error.message.replace(/^Unexpected token/,'无法识别的语法:');errorBox.hidden=false;legend.textContent='y = invalid expression'}draw()}
function toScreen(x,y){const r=canvas.getBoundingClientRect();return{x:r.width/2+(x-view.centerX)*view.scale,y:r.height/2-(y-view.centerY)*view.scale}}
function toWorld(x,y){const r=canvas.getBoundingClientRect();return{x:view.centerX+(x-r.width/2)/view.scale,y:view.centerY-(y-r.height/2)/view.scale}}
function niceStep(){const wanted=90/view.scale,mag=10**Math.floor(Math.log10(wanted)),norm=wanted/mag;return(norm<=1?1:norm<=2?2:norm<=5?5:10)*mag}
function format(n){if(Math.abs(n)>=10||Number.isInteger(n))return String(n);return n.toFixed(Math.min(3,Math.max(0,-Math.floor(Math.log10(Math.abs(n)))+1)))}
function grid(r){const step=niceStep(),startX=Math.floor((view.centerX-r.width/2/view.scale)/step)*step,endX=view.centerX+r.width/2/view.scale,startY=Math.floor((view.centerY-r.height/2/view.scale)/step)*step,endY=view.centerY+r.height/2/view.scale;ctx.lineWidth=1;ctx.strokeStyle='rgba(92,105,122,.18)';ctx.fillStyle='rgba(166,177,191,.68)';ctx.font='10px "DM Mono"';ctx.beginPath();for(let x=startX;x<=endX;x+=step){const p=toScreen(x,0);ctx.moveTo(Math.round(p.x)+.5,0);ctx.lineTo(Math.round(p.x)+.5,r.height)}for(let y=startY;y<=endY;y+=step){const p=toScreen(0,y);ctx.moveTo(0,Math.round(p.y)+.5);ctx.lineTo(r.width,Math.round(p.y)+.5)}ctx.stroke();const origin=toScreen(0,0);ctx.strokeStyle='rgba(209,218,227,.64)';ctx.lineWidth=1.25;ctx.beginPath();ctx.moveTo(0,Math.round(origin.y)+.5);ctx.lineTo(r.width,Math.round(origin.y)+.5);ctx.moveTo(Math.round(origin.x)+.5,0);ctx.lineTo(Math.round(origin.x)+.5,r.height);ctx.stroke();for(let x=startX;x<=endX;x+=step){if(Math.abs(x)<step/10)continue;const p=toScreen(x,0);if(p.x>15&&p.x<r.width-15&&origin.y>12&&origin.y<r.height-3)ctx.fillText(format(x),p.x+4,origin.y-7)}for(let y=startY;y<=endY;y+=step){if(Math.abs(y)<step/10)continue;const p=toScreen(0,y);if(p.y>12&&p.y<r.height-8&&origin.x>3&&origin.x<r.width-22)ctx.fillText(format(y),origin.x+7,p.y-4)}}
function curve(r){if(!evaluator)return;const setMin=Number(xMin.value),setMax=Number(xMax.value),visibleMin=view.centerX-r.width/2/view.scale,visibleMax=view.centerX+r.width/2/view.scale,minX=Number.isFinite(setMin)?Math.max(setMin,visibleMin):visibleMin,maxX=Number.isFinite(setMax)?Math.min(setMax,visibleMax):visibleMax;if(minX>=maxX)return;const paint=stroke=>{ctx.strokeStyle=stroke;ctx.lineWidth=stroke==='#a8ff5d'?2.4:8;ctx.lineJoin='round';ctx.beginPath();let joined=false;for(let i=0;i<samples;i++){const x=minX+(maxX-minX)*i/(samples-1);let y;try{y=evaluator(x,...args)}catch{y=NaN}const p=toScreen(x,y);if(!Number.isFinite(y)||Math.abs(p.y)>r.height*10){joined=false;continue}if(!joined){ctx.moveTo(p.x,p.y);joined=true}else ctx.lineTo(p.x,p.y)}ctx.stroke()};ctx.save();ctx.beginPath();ctx.rect(0,0,r.width,r.height);ctx.clip();paint('rgba(168,255,93,.16)');paint('#a8ff5d');ctx.restore()}
function safeY(x){try{const y=evaluator(x,...args);return Number.isFinite(y)?y:null}catch{return null}}
function mark(){if(!cursor||!evaluator)return;const y=safeY(cursor.x);if(y===null)return;const p=toScreen(cursor.x,y);ctx.setLineDash([4,4]);ctx.strokeStyle='rgba(168,255,93,.35)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,0);ctx.lineTo(p.x,canvas.clientHeight);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#101318';ctx.strokeStyle='#d9ffb7';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.stroke()}
function draw(){const r=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;if(canvas.width!==Math.round(r.width*ratio)||canvas.height!==Math.round(r.height*ratio)){canvas.width=Math.round(r.width*ratio);canvas.height=Math.round(r.height*ratio)}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,r.width,r.height);grid(r);curve(r);mark();empty.hidden=Boolean(evaluator)}
function reset(){view.centerX=.5;view.centerY=.5;view.scale=430;draw()}
function cursorMove(e){const r=canvas.getBoundingClientRect();cursor=toWorld(e.clientX-r.left,e.clientY-r.top);const y=evaluator?safeY(cursor.x):null;readout.textContent='x '+cursor.x.toFixed(3)+' · y '+(y===null?'—':y.toFixed(3));draw()}
editor.addEventListener('input',compile);[xMin,xMax].forEach(input=>input.addEventListener('input',draw));document.querySelectorAll('.function-chip').forEach(button=>button.addEventListener('click',()=>{editor.value=button.dataset.snippet;compile();editor.focus()}));document.querySelector('#reset-view').addEventListener('click',reset);canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),before=toWorld(e.clientX-r.left,e.clientY-r.top);view.scale=Math.min(5000,Math.max(45,view.scale*(e.deltaY<0?1.12:.89)));const after=toWorld(e.clientX-r.left,e.clientY-r.top);view.centerX+=before.x-after.x;view.centerY+=before.y-after.y;draw()},{passive:false});canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:view.centerX,cy:view.centerY};canvas.setPointerCapture(e.pointerId);panel.classList.add('is-dragging')});canvas.addEventListener('pointermove',e=>{if(drag){view.centerX=drag.cx-(e.clientX-drag.x)/view.scale;view.centerY=drag.cy+(e.clientY-drag.y)/view.scale;draw()}else cursorMove(e)});canvas.addEventListener('pointerup',()=>{drag=null;panel.classList.remove('is-dragging')});canvas.addEventListener('pointerleave',()=>{if(!drag){cursor=null;draw()}});window.addEventListener('resize',draw);compile();